# Generated by Django 4.0.6 on 2022-11-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamlead',
            name='email address',
        ),
        migrations.RemoveField(
            model_name='teamlead',
            name='name',
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
