# Generated by Django 4.0.6 on 2022-11-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_teamlead_email address_remove_teamlead_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlead',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
