# Generated by Django 4.0.6 on 2022-11-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_teamlead_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamlead',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
