# Generated by Django 4.0.6 on 2022-11-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamLead',
        ),
    ]
