# Generated by Django 4.0.6 on 2022-11-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_teamlead'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
